version: 2
workflows:
  build:
    jobs:
      - build-lts-12:
          docker:
            - image: node:12
          working_directory: ~/repo
          steps:
            - checkout
            - restore_cache:
                keys:
                  - v1-dependencies-{{ checksum "package.json" }}
                  - v1-dependencies-
            - run: npm ci
            - run: npm test
      - build-lts-10:
          docker:
            - image: node:10
          working_directory: ~/repo
          steps:
            - checkout
            - restore_cache:
                keys:
                  - v1-dependencies-{{ checksum "package.json" }}
                  - v1-dependencies-
            - run: npm ci
            - run: npm test
      - build-lts-8:
          docker:
            - image: node:8
          working_directory: ~/repo
          steps:
            - checkout
            - restore_cache:
                keys:
                  - v1-dependencies-{{ checksum "package.json" }}
                  - v1-dependencies-
            - run: npm ci
            - run: npm test
